### ISSUE TITLE
[QA] config setting overwrite.cli.url does not match

### ISSUE THREAD

**Issue by jnweiger** [owncloud/qnap#36]
Seen with with ownCloud for QNAP 10.8.0 from ownCloud_10.8.0_arm-x41.qpkg (dated 2021-07-27)

After a fresh install, config.php has this:
```
...
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => 'http://localhost/',
  'htaccess.RewriteBase' => '/',
...
```

Expected behaviour: overwrite.cli.url should say either `https://10.90.4.178/owncloud` or `http://10.90.4.178:8080/owncloud`
 
(The trusted_domains setting in config.php looks odd with the port number included, but it is not effective. It is a wildcard setting as defined in overwrite.config.php -- GOOD.)

**Comment by jnweiger** [comment]
Fixing overwrite.cli.url does not help with #30 or #23

**Comment by wkloucek** [comment]
cannot be set as a default since we don't know the ip address / port / hostname of the device in a user's network. But it should be documented how user can set this with the [special QNAP config file](https://github.com/owncloud/qnap-packaging/blob/master/docs/customization.md). It must be ensured that it will not be overwritten by the docker image configuration.

**Comment by wkloucek** [comment]
@EParzefall could you please add a section to the documentation about configuring a static host name and so on for OC on QNAP ( I took the settings from here: https://doc.owncloud.com/server/admin_manual/configuration/server/reverse_proxy_configuration.html#overwrite-parameters).

The user does not need to do this since oC will come in a "dynamic" mode and will adapt to what ever IP address or hostname the user can reach the QNAP device. In some cases like exposing the device to the internet, some people may want to configure it like a "real server"...

The user can configure their settings in the [user.config.php](https://github.com/owncloud/qnap-packaging/blob/master/docs/customization.md#userconfigphp) like this:
```
<?php
$CONFIG = array(
    'overwriteprotocol' => 'https',
    'overwritehost' => '10.90.4.174',
    'overwrite.cli.url' => 'https://10.90.4.174/owncloud/',
);
```

The config report show that the values from the user.config.php are actually applied:
```
{
    ...
    "config": {
        "overwrite.cli.url": "https:\/\/10.90.4.174\/owncloud\/",
        "overwriteprotocol": "https",
        "overwritehost": "10.90.4.174",
        ...
    },
    ...
```

**Comment by EParzefall** [comment]
Thanks for the info, will be added to the docs.

**Comment by jnweiger** [comment]
Retested with https://github.com/owncloud/qnap-packaging/releases/download/v10.8.0.0-rc3/ownCloud_10.8.0.0-r_x86_64.qpkg

* trusted_domains is now without port number. OK.
* a per overwrite.config.php, the environment variable `OWNCLOUD_OVERWRITE_CLI_URL` can be used to control `overwrite.cli.url`. OK
* TODO: check the available docs.

**Comment by wkloucek** [comment]
@jnweiger existing doc is also in this PR https://github.com/owncloud/docs/pull/3792, though I don't know if the trusted_domains is there (to give users an hint when its applicable and when not)
